name: Master push

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test commits
        env:
          REF: ${{github.ref}}
          HEAD_REF: ${{github.head_ref}}
        run: |
          echo $REF
          echo $HEAD_REF
