name: Master push

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test commits
        env:
          REF: ${{github.ref}}
          HEAD_REF: ${{github.head_ref}}
          BASE_REF: ${{github.base_ref}}
          GITHUB_SHA: ${{github.sha}}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo $REF
          echo $HEAD_REF
          echo $BASE_REF
          echo $(git rev-parse --short "$GITHUB_SHA")
