name: Master push

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test commits
        env:
          REF: ${{github.ref}}
          HEAD_REF: ${{github.head_ref}}
          BASE_REF: ${{github.base_ref}}
          GITHUB_SHA: ${{github.sha}}
          GITHUB_CONTEXT: ${{ toJson(github) }}
          MESSAGE: ${{github.event.head_commit.message}}
        run: |
          echo $REF
          echo $HEAD_REF
          echo $BASE_REF
          echo $(git rev-parse --short "$GITHUB_SHA")
          HEAD_BRANCH=$(git branch | grep \* | cut -d ' ' -f2)
          echo $HEAD_BRANCH
          git config --global user.email "ci@github.com"
          git config --global user.name "GitHub CI"
          bash scripts/bump-version.sh "$MESSAGE"
      - name: build project
        id: build_artifact
        run: |
          zip --junk-paths my-artifact README.md
          echo ::set-output name=tag::$(git describe --abbrev=0 --tags)
          echo ::set-output name=tag_message::$(git tag -l --format='%(contents)' $(git describe --abbrev=0))
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.build_artifact.outputs.tag }}
          release_name: ${{ steps.build_artifact.outputs.tag_message }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./my-artifact.zip
          asset_name: my-artifact.zip
          asset_content_type: application/zip
